# TASK-3 [Feature Engineering]   --WIP--

In [1]:
import pandas as pd

In [2]:
df_m=pd.read_csv('merged.csv')
df_m.head()

,Unnamed: 0,id,price_date,price_p1_var,price_p2_var,price_p3_var,price_p1_fix,price_p2_fix,price_p3_fix,activity_new,...,forecast_price_pow_p1,has_gas,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,origin_up,pow_max
0,180,b3916b398e23aa54255564b7676865bc,2015-01-01,0.148825,0.0,0.0,44.266931,0.0,0.0,mpicaaibskkfmxoblmwwwuuwpkecacil,...,44.311378,f,259.76,21.52,21.52,1,129.79,3,lxidpiddsbxsbosboudacockeimpuepw,13.2
1,181,b3916b398e23aa54255564b7676865bc,2015-02-01,0.148825,0.0,0.0,44.266931,0.0,0.0,mpicaaibskkfmxoblmwwwuuwpkecacil,...,44.311378,f,259.76,21.52,21.52,1,129.79,3,lxidpiddsbxsbosboudacockeimpuepw,13.2
2,182,b3916b398e23aa54255564b7676865bc,2015-03-01,0.148825,0.0,0.0,44.266931,0.0,0.0,mpicaaibskkfmxoblmwwwuuwpkecacil,...,44.311378,f,259.76,21.52,21.52,1,129.79,3,lxidpiddsbxsbosboudacockeimpuepw,13.2
3,183,b3916b398e23aa54255564b7676865bc,2015-04-01,0.148825,0.0,0.0,44.266931,0.0,0.0,mpicaaibskkfmxoblmwwwuuwpkecacil,...,44.311378,f,259.76,21.52,21.52,1,129.79,3,lxidpiddsbxsbosboudacockeimpuepw,13.2
4,184,b3916b398e23aa54255564b7676865bc,2015-05-01,0.147664,0.0,0.0,44.266930,0.0,0.0,mpicaaibskkfmxoblmwwwuuwpkecacil,...,44.311378,f,259.76,21.52,21.52,1,129.79,3,lxidpiddsbxsbosboudacockeimpuepw,13.2

In [3]:
#Remember we already deakt with missing values in the previous task

In [4]:
train_output=pd.read_csv('ml_case_training_output.csv')
df=df_merged=df_m.merge(train_output, how='left', on='id')

In [5]:
df.describe()

,Unnamed: 0,price_p1_var,price_p2_var,price_p3_var,price_p1_fix,price_p2_fix,price_p3_fix,cons_12m,cons_gas_12m,cons_last_month,...,forecast_price_energy_p2,forecast_price_pow_p1,imp_cons,margin_gross_pow_ele,margin_net_pow_ele,nb_prod_act,net_margin,num_years_antig,pow_max,churn
count,16159.000000,16159.000000,16159.000000,16159.000000,16159.000000,16159.000000,16159.000000,1.615900e+04,1.615900e+04,16159.000000,...,16159.000000,16159.000000,16159.000000,16159.000000,16159.00000,16159.000000,16159.000000,16159.000000,16159.000000,16159.000000
mean,92142.972214,0.135136,0.066760,0.042909,43.278192,15.039890,9.123437,4.442794e+05,8.992337e+04,46596.398849,...,0.065370,43.302979,321.993489,22.657734,21.88076,1.278297,330.997679,4.236525,27.261439,0.162572
std,55986.258993,0.019712,0.047991,0.035908,4.355704,12.807248,7.801697,1.088639e+06,3.621988e+05,123763.467598,...,0.046080,4.330542,604.136729,27.826847,30.63074,0.627065,787.379201,1.047870,28.050898,0.368986
min,180.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-1.373000e+03,0.000000e+00,0.000000,...,0.000000,40.606701,0.000000,-41.160000,-293.49000,1.000000,-1523.390000,1.000000,6.600000,0.000000
25%,39769.500000,0.120087,0.000000,0.000000,40.728885,0.000000,0.000000,1.510700e+04,0.000000e+00,604.000000,...,0.000000,40.606701,0.000000,7.040000,6.93000,1.000000,83.825000,3.000000,13.200000,0.000000
50%,96031.000000,0.128649,0.097380,0.068840,40.728885,24.339578,16.226383,4.675900e+04,0.000000e+00,3929.000000,...,0.093746,40.939027,127.150000,20.000000,19.92000,1.000000,198.560000,4.000000,16.500000,0.000000
75%,138633.500000,0.148468,0.103116,0.073487,44.444710,24.437330,16.291555,2.625210e+05,0.000000e+00,19666.000000,...,0.099419,44.311378,394.290000,29.850000,29.76000,1.000000,441.530000,5.000000,29.700000,0.000000
max,192893.000000,0.280700,0.169536,0.114102,59.444710,36.490689,16.958222,6.286272e+06,4.188440e+06,771203.000000,...,0.168092,59.266378,9682.890000,314.760000,314.76000,8.000000,24570.650000,9.000000,331.060000,1.000000

In [6]:
# Train, Validation and Test set for Models
###############################################################################################


train_val=df.drop(columns='churn')


test=df['churn']

# print the size of each
print("train_val",train_val.shape)
print("Test",test.shape)

train_val (16159, 39)
Test (16159,)

In [7]:
#  Normalisation of the numeric columns
###############################################################################################
from sklearn.preprocessing import StandardScaler

numerical_cols = list(set(train_val.select_dtypes('number').columns) - set(['price_date','activity_new','channel_sales',
                                                                            'date_activ','date_end','date_first_activ',
                                                                            'date_modif_prod','date_renewal','has_gas',
                                                                            'origin_up']) )

print("numerical_cols",numerical_cols)

numerical_cols ['forecast_base_bill_year', 'cons_12m', 'price_p3_var', 'imp_cons', 'price_p1_var', 'forecast_cons_12m', 'price_p3_fix', 'forecast_price_energy_p1', 'price_p2_fix', 'nb_prod_act', 'price_p2_var', 'forecast_cons', 'margin_gross_pow_ele', 'forecast_price_pow_p1', 'forecast_discount_energy', 'cons_gas_12m', 'forecast_price_energy_p2', 'forecast_meter_rent_12m', 'price_p1_fix', 'forecast_bill_12m', 'margin_net_pow_ele', 'cons_last_month', 'pow_max', 'forecast_cons_year', 'num_years_antig', 'net_margin', 'Unnamed: 0', 'forecast_base_bill_ele']

In [8]:
for n in numerical_cols:
  scaler = StandardScaler()
  scaler.fit(train_val[n].values.reshape(-1,1))

  train_val_std = scaler.transform(train_val[n].values.reshape(-1,1))

  # Add it to the dataframe
  train_val_std_df = pd.DataFrame(train_val_std,index = train_val.index,columns = [n + "_std"])
  train_val = pd.concat([train_val, train_val_std_df], axis=1)


# remove the original column from the dataframe
train_val.drop(numerical_cols, inplace=True, axis=1) 

display(train_val.head())
display(test.head())

,id,price_date,activity_new,channel_sales,date_activ,date_end,date_first_activ,date_modif_prod,date_renewal,has_gas,...,price_p1_fix_std,forecast_bill_12m_std,margin_net_pow_ele_std,cons_last_month_std,pow_max_std,forecast_cons_year_std,num_years_antig_std,net_margin_std,Unnamed: 0_std,forecast_base_bill_ele_std
0,b3916b398e23aa54255564b7676865bc,2015-01-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.227006,-0.501776,-0.011778,-0.362157,-0.501299,-0.240161,-1.180072,-0.255549,-1.642650,-0.188979
1,b3916b398e23aa54255564b7676865bc,2015-02-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.227006,-0.501776,-0.011778,-0.362157,-0.501299,-0.240161,-1.180072,-0.255549,-1.642632,-0.188979
2,b3916b398e23aa54255564b7676865bc,2015-03-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.227006,-0.501776,-0.011778,-0.362157,-0.501299,-0.240161,-1.180072,-0.255549,-1.642614,-0.188979
3,b3916b398e23aa54255564b7676865bc,2015-04-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.227006,-0.501776,-0.011778,-0.362157,-0.501299,-0.240161,-1.180072,-0.255549,-1.642596,-0.188979
4,b3916b398e23aa54255564b7676865bc,2015-05-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.227006,-0.501776,-0.011778,-0.362157,-0.501299,-0.240161,-1.180072,-0.255549,-1.642578,-0.188979

0    0
1    0
2    0
3    0
4    0
Name: churn, dtype: int64

In [9]:
# One hot encoding of the categorical columns on datasets
###############################################################################################
from sklearn.preprocessing import OneHotEncoder
import pandas as pd

onehotencoder = OneHotEncoder()
# Categorical values for encoding
categorical_cols = ['price_date','activity_new','channel_sales','date_activ','date_end','date_first_activ',
                    'date_modif_prod','date_renewal','has_gas','origin_up']

for c in categorical_cols:
  onehotencoder.fit(train_val[c].values.reshape(-1,1))

  train_val_categorical = onehotencoder.transform(train_val[c].values.reshape(-1,1)).toarray()

  # Add to the dataframe back
  train_val_onehot_df = pd.DataFrame(train_val_categorical,index = train_val.index,columns = [c + str(int(i)) for i in range(train_val_categorical.shape[1])])
  train_val = pd.concat([train_val, train_val_onehot_df], axis=1)

  #test_onehot_df = pd.DataFrame(test_categorical,index = test.index,columns = [c + str(int(i)) for i in range(test_categorical.shape[1])])
  #test = pd.concat([test, test_onehot_df], axis=1)

display(train_val.head())
display(test.head())

# ### need to handle multi-collinearity seperately

,id,price_date,activity_new,channel_sales,date_activ,date_end,date_first_activ,date_modif_prod,date_renewal,has_gas,...,date_renewal270,date_renewal271,date_renewal272,date_renewal273,date_renewal274,date_renewal275,has_gas0,has_gas1,origin_up0,origin_up1
0,b3916b398e23aa54255564b7676865bc,2015-01-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1,b3916b398e23aa54255564b7676865bc,2015-02-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
2,b3916b398e23aa54255564b7676865bc,2015-03-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
3,b3916b398e23aa54255564b7676865bc,2015-04-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
4,b3916b398e23aa54255564b7676865bc,2015-05-01,mpicaaibskkfmxoblmwwwuuwpkecacil,ewpakwlliwisiwduibdlfmalxowmwpci,2013-06-05,2016-06-05,2012-03-02,2015-04-29,2015-06-14,f,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

0    0
1    0
2    0
3    0
4    0
Name: churn, dtype: int64

In [12]:
#  Create train and validation set and label set - remove not needed columns
###############################################################################################

# take only the features needed for training/testing
train_val  = train_val.iloc[:,11:]


# # print the size of each

#
from sklearn.model_selection import train_test_split

train_x,test_x,train_y,test_y=train_test_split(train_val,test,test_size=0.20,random_state=2)
print("Train",train_x.shape)
print("Test",test_x.shape)

display(train_x.head())
display(train_y.head())

Train (12927, 2857)
Test (3232, 2857)

,forecast_cons_std,margin_gross_pow_ele_std,forecast_price_pow_p1_std,forecast_discount_energy_std,cons_gas_12m_std,forecast_price_energy_p2_std,forecast_meter_rent_12m_std,price_p1_fix_std,forecast_bill_12m_std,margin_net_pow_ele_std,...,date_renewal270,date_renewal271,date_renewal272,date_renewal273,date_renewal274,date_renewal275,has_gas0,has_gas1,origin_up0,origin_up1
9288,-0.334378,2.148433,-0.622638,-0.186473,-0.248278,0.713818,0.590605,-0.585298,-0.357267,1.977135,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
15288,-0.439771,1.277305,-0.622638,-0.186473,-0.248278,0.751862,0.610959,-0.585298,-0.485627,1.185749,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
5865,0.185835,-0.206201,-0.622638,-0.186473,-0.248278,0.726297,1.969862,-0.622702,-0.073990,-0.161959,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
11478,-0.532998,-0.372232,0.232865,-0.186473,-0.248278,-1.418682,-1.124174,0.227006,-0.659441,-0.312792,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
6789,0.101349,-0.098388,-0.622638,-0.186473,-0.248278,0.763950,0.608557,-0.585298,-0.233135,-0.064015,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0

9288     1
15288    1
5865     0
11478    0
6789     0
Name: churn, dtype: int64

In [13]:
from xgboost import XGBClassifier
from xgboost import plot_importance
from matplotlib import pyplot
from numpy import sort
from sklearn.metrics import accuracy_score
from sklearn.feature_selection import SelectFromModel

ModuleNotFoundError: No module named 'xgboost'

In [14]:
import warnings
warnings.filterwarnings("ignore")

model = XGBClassifier()
model.fit(train_x, train_y)
predictions = model.predict(test_x)
accuracy = accuracy_score(test_y, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

# Fit model using each importance as a threshold
thresholds = sort(model.feature_importances_)
for thresh in thresholds:
    selection = SelectFromModel(model, threshold=thresh, prefit=True)
    select_X_train = selection.transform(train_x)
    # train model
    selection_model = XGBClassifier()
    selection_model.fit(select_X_train, train_y)
    # eval model
    select_X_test = selection.transform(test_x)
    predictions = selection_model.predict(select_X_test)
    accuracy = accuracy_score(test_y, predictions)
    print("Thresh=%.3f, n=%d, Accuracy: %.2f%%" % (thresh, select_X_train.shape[1], accuracy*100.0))




plot_importance(model)
pyplot.show()

NameError: name 'XGBClassifier' is not defined